export const ADD_COLOR = 'ADD_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const SELECT_COLOR_LIST = 'SELECT_COLOR_LIST';
export const ADD_COLOR_LIST = 'ADD_COLOR_LIST';
export const SELECT_COLOR = 'SELECT_COLOR';
export const UPDATE_COLOR_LIGHTNESS = 'UPDATE_COLOR_LIGHTNESS';
export const UPDATE_COLOR_SATURATION = 'UPDATE_COLOR_SATURATION';
export const UPDATE_COLOR_HUE = 'UPDATE_COLOR_HUE';
